# ===============================================
# OpenAI Codex PR Configuration
# Тихий режим / Без эмодзи / Без label / Без авто-approve
# ===============================================

# 👇 Основные настройки Codex
label: false                # Отключает автоматическую метку "codex"
reactions: false            # Отключает emoji-реакции (👀, 👍 и т.д.)
auto_approve: false         # Не одобрять PR автоматически
auto_merge: false           # Не выполнять авто-мёрдж
assign_reviewer: false      # Не назначать ревьюеров автоматически
update_existing_pr: true    # Codex обновляет свой PR, если он уже есть

# 👇 Настройки PR
pr:
  title_prefix: "[Codex]"   # Префикс для PR (можно убрать)
  branch_prefix: "codex/"   # Ветка, куда Codex будет пушить свои изменения
  body_template: |-
    🤖 *Этот PR создан OpenAI Codex.*

    Изменения автоматически сгенерированы.  
    Проверьте корректность перед слиянием.
  delete_branch_after_merge: true

# 👇 Настройки коммитов
commits:
  message_format: "Codex: {{summary}}"  # Формат commit message
  signoff: false                        # Не добавлять DCO/Signoff

# 👇 Настройки обзоров (reviews)
reviews:
  emojis: false          # Не ставить эмодзи при просмотре
  comments: false        # Не оставлять комментарии в коде
  summary_comment: false # Не оставлять общий комментарий в PR

# 👇 Настройки безопасности
permissions:
  write: false            # Codex не изменяет чужие ветки
  delete: false           # Codex не удаляет ничего вне своей ветки

# ===============================================
# Конец конфигурации
# ===============================================
