name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install build flake8 pytest mypy yamllint

      - name: Lint (flake8)
        run: |
          flake8 modules secaudit utils tests --max-line-length=120 --exclude __init__.py

      - name: Type check (mypy)
        run: |
          mypy modules secaudit utils tests --ignore-missing-imports

      - name: Lint YAML
        run: |
          yamllint profiles workflows

      - name: Tests (pytest)
        run: |
          pytest -q

      - name: Build sdist/wheel
        run: |
          python -m build
          ls -lah dist

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: secaudit-dist
          path: dist/*
